"""
Semiconductor Yield Fault Detection — Streamlit dashboard.

A five-page tool for working with a trained pass/fail classifier on the
SECOM semiconductor dataset:

  1. Wafer Diagnostic    — drill into one wafer (prediction + SHAP + Z-score)
  2. Compare Wafers      — side-by-side diff of two wafers' SHAP signatures
  3. Aggregate Metrics   — model-wide precision/recall/ROC at any threshold
  4. Failure Clustering  — K-means on SHAP signatures to surface failure modes
  5. Drift Monitor       — PSI + KS test of a recent batch vs. training data

Run:  streamlit run app/streamlit_app.py
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from src.diagnostics import DiagnosticsPipeline, generate_root_cause_summary
from src.drift import compute_drift_report

# ─── Page config ──────────────────────────────────────────

st.set_page_config(
    page_title="Yield Fault Detection",
    page_icon="🔬",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─── Dark-mode Plotly template ────────────────────────────

PLOTLY_LAYOUT = dict(
    template="plotly_dark",
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="rgba(0,0,0,0)",
    font=dict(family="sans-serif", color="#E0E0E0"),
)

COLORS = {
    "fail": "#EF5350",
    "pass": "#4FC3F7",
    "warn": "#FFA726",
    "ok": "#66BB6A",
    "bar_baseline": "#4FC3F7",
    "sample_marker": "#EF5350",
}

# ─── Pipeline loading (cached) ───────────────────────────

@st.cache_resource
def load_pipeline():
    """
    Load pipeline artifacts. Checks dashboard_assets/ first (committed to repo
    for zero-setup demos), then falls back to the standard data/ + models/ paths
    (generated by notebooks and train.py).
    """
    assets_dir = os.path.join(os.path.dirname(__file__), "..", "dashboard_assets")
    if os.path.isdir(os.path.join(assets_dir, "models")) and \
       os.path.isdir(os.path.join(assets_dir, "data")):
        model_dir = os.path.join(assets_dir, "models")
        data_dir = os.path.join(assets_dir, "data")
    else:
        model_dir = "models"
        data_dir = "data/processed"

    pipeline = DiagnosticsPipeline(model_dir=model_dir, data_dir=data_dir)
    pipeline.load()
    return pipeline


@st.cache_data(show_spinner=False)
def _diagnose_cached(_pipeline, index: int, top_k: int = 10):
    """Memoize per-wafer diagnostics so re-renders don't re-run SHAP."""
    return _pipeline.diagnose_by_index(index, top_k=top_k)


@st.cache_data(show_spinner="Computing predictions for all wafers...")
def _predict_all(_pipeline) -> pd.DataFrame:
    """Run the model over the full dataset for aggregate-metrics / clustering pages."""
    import numpy as np

    X_raw = _pipeline._X_clean
    X_proc = _pipeline._transform(X_raw)
    probs = _pipeline.model.predict_proba(X_proc)[:, 1]
    preds = (probs >= _pipeline.threshold).astype(int)
    return pd.DataFrame({
        "wafer_index": np.arange(len(probs)),
        "actual": _pipeline._y.values,
        "probability": probs,
        "prediction": preds,
    })


@st.cache_data(show_spinner="Computing SHAP signatures for all failures...")
def _failure_shap_matrix(_pipeline) -> pd.DataFrame:
    """SHAP values for every failed wafer — used by the clustering page."""
    rows = {}
    for idx in _pipeline.fail_indices:
        try:
            diag = _pipeline.diagnose_by_index(idx, top_k=50)
            rows[idx] = diag.shap_values
        except Exception:
            continue
    return pd.DataFrame(rows).T


def render_compare_page(pipeline):
    """Side-by-side comparison of two wafers."""
    st.title("Compare Two Wafers")
    st.markdown(
        "**When to use this view:** *Why did this wafer fail when that one passed?* "
        "Pick any two wafers — typically one failure and one healthy reference — "
        "and see exactly what's different about their sensor patterns. The chart "
        "shows, per sensor, how strongly each one pushed each wafer toward FAIL "
        "(check the legend to see which color is which wafer). Sensors with very "
        "different bars between the two wafers are the ones to focus on. The table "
        "at the bottom ranks those differences by absolute size."
    )

    col_a, col_b = st.columns(2)
    with col_a:
        idx_a = st.number_input(
            "Wafer A", min_value=1, max_value=pipeline.n_samples, value=1, step=1,
        ) - 1
    with col_b:
        default_b = pipeline.fail_indices[0] + 1 if pipeline.fail_indices else 2
        idx_b = st.number_input(
            "Wafer B", min_value=1, max_value=pipeline.n_samples, value=default_b, step=1,
        ) - 1

    diag_a = _diagnose_cached(pipeline, int(idx_a), top_k=10)
    diag_b = _diagnose_cached(pipeline, int(idx_b), top_k=10)

    st.markdown("### Predictions")
    m1, m2, m3, m4 = st.columns(4)
    m1.metric(
        f"Wafer {idx_a + 1}",
        diag_a.prediction,
        delta=f"{diag_a.probability:.1%} fail prob",
        delta_color="inverse",
    )
    m2.metric(
        "Actual A",
        "FAIL" if pipeline.get_label(int(idx_a)) == 1 else "PASS",
    )
    m3.metric(
        f"Wafer {idx_b + 1}",
        diag_b.prediction,
        delta=f"{diag_b.probability:.1%} fail prob",
        delta_color="inverse",
    )
    m4.metric(
        "Actual B",
        "FAIL" if pipeline.get_label(int(idx_b)) == 1 else "PASS",
    )

    st.markdown("### SHAP — sensor contributions side by side")
    union = list(dict.fromkeys(diag_a.top_shap_features[:8] + diag_b.top_shap_features[:8]))
    shap_a = [float(diag_a.shap_values[f]) for f in union]
    shap_b = [float(diag_b.shap_values[f]) for f in union]

    fig = go.Figure()
    fig.add_trace(go.Bar(
        name=f"Wafer {idx_a + 1}", x=shap_a, y=union, orientation="h",
        marker_color=COLORS["pass"],
    ))
    fig.add_trace(go.Bar(
        name=f"Wafer {idx_b + 1}", x=shap_b, y=union, orientation="h",
        marker_color=COLORS["fail"],
    ))
    fig.update_layout(
        barmode="group",
        xaxis_title="SHAP value (push toward FAIL →)",
        yaxis_title="Sensor",
        height=max(400, len(union) * 35),
        margin=dict(l=20, r=20, t=20, b=40),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        **PLOTLY_LAYOUT,
    )
    st.plotly_chart(fig, use_container_width=True)

    st.markdown("### Z-score deviations (vs healthy baseline)")
    diff_rows = []
    for f in union:
        diff_rows.append({
            "Sensor": f,
            f"Z-Score (Wafer {idx_a + 1})": round(float(diag_a.deviations_z[f]), 2),
            f"Z-Score (Wafer {idx_b + 1})": round(float(diag_b.deviations_z[f]), 2),
            "|Difference|": round(abs(
                float(diag_a.deviations_z[f]) - float(diag_b.deviations_z[f])
            ), 2),
        })
    diff_df = pd.DataFrame(diff_rows).sort_values("|Difference|", ascending=False)
    st.dataframe(diff_df, use_container_width=True, hide_index=True)


def render_metrics_page(pipeline):
    """Confusion matrix + ROC + PR curve at a user-tunable threshold."""
    import numpy as np
    from sklearn.metrics import (
        average_precision_score,
        confusion_matrix,
        precision_recall_curve,
        roc_auc_score,
        roc_curve,
    )

    st.title("Aggregate Model Metrics")
    st.markdown(
        "**When to use this view:** *How good is the model overall, and what's "
        "the trade-off?* Catching every failure (high **recall**) usually means "
        "raising more false alarms (lower **precision**), and vice versa. The "
        "**decision threshold** below is the dial that controls that trade-off — "
        "drag it and watch every metric and chart on the page update live."
    )

    with st.expander("How to read this page (quick glossary)"):
        st.markdown(
            "- **Decision threshold** — the failure probability above which the "
            "model says \"FAIL.\" Lower threshold → more wafers flagged (catches "
            "more real failures but more false alarms). Higher threshold → fewer "
            "alarms but you miss more failures.\n"
            "- **Precision (Fail)** — *of the wafers we flagged, what fraction "
            "actually failed?* High precision = few false alarms.\n"
            "- **Recall (Fail)** — *of the wafers that actually failed, what "
            "fraction did we catch?* High recall = few escapes to the customer.\n"
            "- **F1** — harmonic mean of precision and recall (single balanced score).\n"
            "- **ROC-AUC** — overall ranking quality, threshold-independent. "
            "1.0 is perfect, 0.5 is random guessing.\n"
            "- **Confusion matrix** — counts of correct vs. wrong calls:\n"
            "    - **TN** (true negative) = healthy wafer correctly cleared\n"
            "    - **TP** (true positive) = failure correctly caught\n"
            "    - **FP** (false positive) = false alarm (healthy wafer flagged)\n"
            "    - **FN** (false negative) = missed failure (escaped to customer)"
        )

    preds = _predict_all(pipeline)
    y_true = preds["actual"].values
    y_prob = preds["probability"].values

    threshold = st.slider(
        "Decision threshold",
        min_value=0.0, max_value=1.0,
        value=float(pipeline.threshold),
        step=0.01,
        help=f"Tuned threshold from training: {pipeline.threshold:.3f}",
    )
    y_pred = (y_prob >= threshold).astype(int)

    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel()
    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0

    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Precision (Fail)", f"{precision:.2%}")
    m2.metric("Recall (Fail)", f"{recall:.2%}")
    m3.metric("F1 (Fail)", f"{f1:.3f}")
    m4.metric("ROC-AUC", f"{roc_auc_score(y_true, y_prob):.3f}")

    col_cm, col_curves = st.columns([1, 2])

    with col_cm:
        st.markdown("#### Confusion matrix")
        cm_z = [[int(tn), int(fp)], [int(fn), int(tp)]]
        # Per-cell text color: white on dark fills, near-black on light fills,
        # so labels stay readable regardless of cell magnitude on the Blues scale.
        cm_max = max(int(tn), int(fp), int(fn), int(tp), 1)
        threshold_intensity = 0.5
        cm_text_colors = [
            [
                "#FFFFFF" if (cm_z[i][j] / cm_max) >= threshold_intensity else "#0E1117"
                for j in range(2)
            ]
            for i in range(2)
        ]
        fig_cm = go.Figure()
        fig_cm.add_trace(go.Heatmap(
            z=cm_z,
            x=["Pred PASS", "Pred FAIL"],
            y=["Actual PASS", "Actual FAIL"],
            colorscale="Blues",
            showscale=False,
            hovertemplate="%{y} / %{x}: %{z}<extra></extra>",
        ))
        labels = [["TN", "FP"], ["FN", "TP"]]
        for i in range(2):
            for j in range(2):
                fig_cm.add_annotation(
                    x=["Pred PASS", "Pred FAIL"][j],
                    y=["Actual PASS", "Actual FAIL"][i],
                    text=f"<b>{labels[i][j]}</b><br>{cm_z[i][j]}",
                    showarrow=False,
                    font=dict(size=14, color=cm_text_colors[i][j]),
                )
        fig_cm.update_layout(height=320, margin=dict(l=20, r=20, t=20, b=20), **PLOTLY_LAYOUT)
        st.plotly_chart(fig_cm, use_container_width=True)

    with col_curves:
        st.markdown("#### ROC and Precision-Recall curves")
        fpr, tpr, roc_thr = roc_curve(y_true, y_prob)
        prec, rec, pr_thr = precision_recall_curve(y_true, y_prob)
        ap = average_precision_score(y_true, y_prob)

        # Operating point on each curve
        op_idx_roc = int(np.argmin(np.abs(roc_thr - threshold))) if len(roc_thr) else 0
        op_idx_pr = int(np.argmin(np.abs(pr_thr - threshold))) if len(pr_thr) else 0

        fig_curves = go.Figure()
        fig_curves.add_trace(go.Scatter(
            x=fpr, y=tpr, mode="lines",
            name=f"ROC (AUC={roc_auc_score(y_true, y_prob):.3f})",
            line=dict(color=COLORS["pass"]),
        ))
        fig_curves.add_trace(go.Scatter(
            x=rec, y=prec, mode="lines",
            name=f"PR (AP={ap:.3f})",
            line=dict(color=COLORS["fail"]),
        ))
        fig_curves.add_trace(go.Scatter(
            x=[fpr[op_idx_roc], rec[op_idx_pr]],
            y=[tpr[op_idx_roc], prec[op_idx_pr]],
            mode="markers",
            name=f"Operating point (thr={threshold:.2f})",
            marker=dict(size=12, color="#FFFFFF", symbol="diamond"),
            showlegend=True,
        ))
        fig_curves.update_layout(
            xaxis_title="FPR (ROC) / Recall (PR)",
            yaxis_title="TPR (ROC) / Precision (PR)",
            height=400,
            margin=dict(l=20, r=20, t=20, b=40),
            legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
            **PLOTLY_LAYOUT,
        )
        st.plotly_chart(fig_curves, use_container_width=True)

    with st.expander("Probability distribution by actual class"):
        fig_dist = go.Figure()
        fig_dist.add_trace(go.Histogram(
            x=y_prob[y_true == 0], name="Actual PASS",
            marker_color=COLORS["pass"], opacity=0.7, nbinsx=40,
        ))
        fig_dist.add_trace(go.Histogram(
            x=y_prob[y_true == 1], name="Actual FAIL",
            marker_color=COLORS["fail"], opacity=0.7, nbinsx=40,
        ))
        fig_dist.add_vline(x=threshold, line_dash="dash", line_color="#FFFFFF",
                           annotation_text=f"thr={threshold:.2f}")
        fig_dist.update_layout(
            xaxis_title="Predicted failure probability",
            yaxis_title="Count",
            barmode="overlay",
            height=350, margin=dict(l=20, r=20, t=20, b=40),
            **PLOTLY_LAYOUT,
        )
        st.plotly_chart(fig_dist, use_container_width=True)


def render_clustering_page(pipeline):
    """K-means clustering of failures by their SHAP signatures."""
    from sklearn.cluster import KMeans
    from sklearn.decomposition import PCA

    st.title("Failure Pattern Clustering")
    st.markdown(
        "**When to use this view:** *Are all failures the same root cause, or "
        "are there a few distinct patterns?* Treating every defect as one big "
        "category hides the structure — in practice you usually have, say, a "
        "thermal-instability cluster, a pressure-related cluster, and a "
        "contamination cluster, each needing a different fix.\n\n"
        "This page takes every failed wafer, looks at *which sensors drove its "
        "failure* (its SHAP \"signature\"), and groups wafers with similar "
        "signatures together using K-means clustering. Each group is a "
        "**failure mode**. The scatter plot below is a 2-D projection (PCA) "
        "of those signatures so groups are visible at a glance — the table "
        "underneath lists the top driver sensors per mode, which tells you "
        "*what's distinctive* about each one."
    )

    fail_shap = _failure_shap_matrix(pipeline)
    if fail_shap.empty:
        st.warning("No failures available for clustering.")
        return

    st.markdown(
        f"Clustering **{len(fail_shap)} failed wafers** by their SHAP signatures."
    )

    n_clusters = st.slider("Number of clusters (failure modes)", 2, 6, 3)
    km = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
    labels = km.fit_predict(fail_shap.values)

    pca = PCA(n_components=2, random_state=42)
    coords = pca.fit_transform(fail_shap.values)

    plot_df = pd.DataFrame({
        "wafer": [int(i) + 1 for i in fail_shap.index],
        "PC1": coords[:, 0],
        "PC2": coords[:, 1],
        "cluster": [f"Mode {c + 1}" for c in labels],
    })

    palette = ["#EF5350", "#FFA726", "#4FC3F7", "#AB47BC", "#66BB6A", "#FFCA28"]
    fig = go.Figure()
    for cid in sorted(plot_df["cluster"].unique()):
        sub = plot_df[plot_df["cluster"] == cid]
        fig.add_trace(go.Scatter(
            x=sub["PC1"], y=sub["PC2"], mode="markers",
            name=cid,
            marker=dict(size=10, color=palette[int(cid.split()[-1]) - 1]),
            text=[f"Wafer {w}" for w in sub["wafer"]],
            hovertemplate="%{text}<br>PC1=%{x:.2f}, PC2=%{y:.2f}<extra></extra>",
        ))
    fig.update_layout(
        xaxis_title=f"PC1 ({pca.explained_variance_ratio_[0]:.0%} var)",
        yaxis_title=f"PC2 ({pca.explained_variance_ratio_[1]:.0%} var)",
        height=500, margin=dict(l=20, r=20, t=20, b=40),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        **PLOTLY_LAYOUT,
    )
    st.plotly_chart(fig, use_container_width=True)

    st.markdown("### Top driver sensors per failure mode")
    centroid_df = pd.DataFrame(km.cluster_centers_, columns=fail_shap.columns)

    for cid in range(n_clusters):
        n_in = int((labels == cid).sum())
        with st.expander(f"Mode {cid + 1} — {n_in} wafers"):
            top_drivers = (
                centroid_df.iloc[cid]
                .reindex(centroid_df.iloc[cid].abs().sort_values(ascending=False).index)
                .head(8)
            )
            members = [
                int(i) + 1
                for i, lbl in zip(fail_shap.index, labels, strict=True)
                if lbl == cid
            ]

            fig_top = go.Figure(go.Bar(
                x=top_drivers.values[::-1],
                y=top_drivers.index[::-1],
                orientation="h",
                marker_color=[
                    COLORS["fail"] if v > 0 else COLORS["pass"]
                    for v in top_drivers.values[::-1]
                ],
            ))
            fig_top.update_layout(
                xaxis_title="Mean SHAP value",
                height=max(250, 35 * len(top_drivers)),
                margin=dict(l=20, r=20, t=10, b=40),
                **PLOTLY_LAYOUT,
            )
            st.plotly_chart(fig_top, use_container_width=True)

            st.markdown(
                f"**Wafers in this mode:** {', '.join(str(m) for m in members[:30])}"
                + (f" *(+{len(members) - 30} more)*" if len(members) > 30 else "")
            )


def render_drift_page(pipeline):
    """Population Stability Index + KS test against the training baseline."""
    st.title("Drift Monitor")
    st.markdown(
        "**When to use this view:** *Has the production line changed since we "
        "trained the model?* Manufacturing processes drift over time — sensor "
        "calibrations change, raw-material lots vary, equipment ages. When the "
        "live data starts to look meaningfully different from what the model "
        "was trained on, predictions stop being reliable and the model needs "
        "retraining.\n\n"
        "This page compares a recent batch of wafers (you choose) against the "
        "training data, sensor by sensor. Each sensor gets two scores:\n\n"
        "- **PSI (Population Stability Index)** — *how shifted is the "
        "distribution?* Industry-standard thresholds: **< 0.10 stable**, "
        "**0.10–0.25 moderate drift**, **> 0.25 significant drift** (retrain).\n"
        "- **KS test** — a statistical p-value for \"these two samples came "
        "from the same distribution.\" Tiny p-value → they didn't.\n\n"
        "The summary cards and bar chart below tell you, at a glance, how many "
        "sensors have drifted and which ones drifted the most."
    )

    st.markdown("### Choose a comparison")
    mode = st.radio(
        "Source for the recent batch",
        [
            "Use a slice of the dataset (demo)",
            "Upload a CSV of recent wafers",
        ],
        horizontal=True,
        label_visibility="collapsed",
    )

    reference = pipeline._X_clean  # full training distribution

    current = None
    if mode == "Use a slice of the dataset (demo)":
        col_a, col_b = st.columns([2, 1])
        with col_a:
            n_slice = st.slider(
                "Number of wafers in the recent batch",
                min_value=50, max_value=min(500, pipeline.n_samples - 50),
                value=200, step=50,
            )
        with col_b:
            tail = st.checkbox(
                "Take the last N (vs random sample)",
                value=True,
                help="The last N wafers of the dataset simulate the most-recent production batch.",
            )
        current = reference.tail(n_slice) if tail else reference.sample(n_slice, random_state=0)
    else:
        uploaded = st.file_uploader(
            "Upload a CSV with the same 446 columns as X_clean.csv",
            type=["csv"],
        )
        if uploaded is not None:
            try:
                current = pd.read_csv(uploaded)
                missing = set(reference.columns) - set(current.columns)
                if missing:
                    st.error(
                        f"Uploaded CSV is missing {len(missing)} column(s) "
                        f"(showing first 5): {sorted(missing)[:5]}"
                    )
                    current = None
            except Exception as e:  # noqa: BLE001
                st.error(f"Failed to read CSV: {e}")
                current = None

    if current is None or len(current) == 0:
        st.info("Pick a batch above to run drift analysis.")
        return

    st.markdown(
        f"**Reference (training):** {len(reference):,} wafers &nbsp;&nbsp;|&nbsp;&nbsp; "
        f"**Current batch:** {len(current):,} wafers"
    )

    with st.spinner("Computing PSI + KS for 446 features..."):
        report = compute_drift_report(reference, current)

    c1, c2, c3 = st.columns(3)
    with c1:
        st.metric("Significant drift (PSI > 0.25)", report.n_significant)
    with c2:
        st.metric("Moderate drift (0.10–0.25)", report.n_moderate)
    with c3:
        no_drift = len(report.per_feature) - report.n_significant - report.n_moderate
        st.metric("Stable (PSI < 0.10)", no_drift)

    st.markdown("### Top 25 most-drifted sensors")
    top = report.per_feature.head(25).reset_index()

    severity_color = {
        "significant": COLORS["fail"],
        "moderate": COLORS["warn"],
        "none": COLORS["ok"],
        "unknown": "#888888",
    }
    bar_colors = [severity_color.get(s, "#888888") for s in top["severity"]]

    fig = go.Figure(go.Bar(
        x=top["psi"][::-1],
        y=top["feature"][::-1],
        orientation="h",
        marker_color=bar_colors[::-1],
        text=[f"{v:.3f}" for v in top["psi"][::-1]],
        textposition="auto",
        textfont=dict(color="#E0E0E0"),
    ))
    fig.add_vline(x=0.10, line_dash="dash", line_color="#FFA726", opacity=0.7,
                  annotation_text="moderate", annotation_position="top")
    fig.add_vline(x=0.25, line_dash="dash", line_color="#EF5350", opacity=0.7,
                  annotation_text="significant", annotation_position="top")
    fig.update_layout(
        xaxis_title="PSI",
        yaxis_title="Sensor",
        height=max(400, len(top) * 22),
        margin=dict(l=20, r=20, t=40, b=40),
        **PLOTLY_LAYOUT,
    )
    st.plotly_chart(fig, use_container_width=True)

    with st.expander("Full per-feature drift table"):
        st.dataframe(report.per_feature.reset_index(), use_container_width=True, hide_index=True)


def main():
    # ── Header ────────────────────────────────────────────
    st.title("Semiconductor Yield Fault Detection")
    st.markdown(
        "**What is this?** A semiconductor wafer is a thin slice of silicon that "
        "future microchips are built on. As each wafer moves through a production "
        "line, hundreds of sensors record temperature, pressure, gas flow, voltages, "
        "and so on. After production, a quality test marks the wafer as **PASS** or "
        "**FAIL**.\n\n"
        "**What this tool does.** It uses a trained machine-learning model to "
        "predict pass/fail from sensor readings *and* explain its reasoning — "
        "which sensors looked most suspicious, and how far off they were from a "
        "healthy baseline. That makes it useful both for **catching failures "
        "early** and for **pointing engineers at the right sensors to investigate**."
    )

    st.info(
        "Use the **View** menu in the sidebar to switch between five tools — "
        "from drilling into a single wafer to monitoring the production line as a whole."
    )

    with st.expander("About this project & dataset"):
        st.markdown(
            "This dashboard is built on the [SECOM dataset](https://archive.ics.uci.edu/dataset/179/secom) "
            "from the UCI Machine Learning Repository. The data was collected from a real semiconductor "
            "manufacturing line — each of the 1,567 wafers has 590 sensor readings captured during "
            "production, along with a pass/fail quality label. The sensor names are anonymized to "
            "protect proprietary process details, so they appear as numeric IDs (e.g. Feature 1, "
            "Feature 155) rather than physical sensor names.\n\n"
            "Only ~6.6% of wafers in the dataset failed inspection, making this a heavily imbalanced "
            "classification problem (a model that always guessed 'PASS' would be 93% accurate "
            "while catching zero failures — so accuracy alone is misleading). The ML pipeline behind "
            "this dashboard reduces the 590 raw sensors down to the 50 most informative features using "
            "variance filtering, correlation pruning, and mutual-information ranking, then trains a "
            "class-weighted Random Forest with a recall-tuned decision threshold to handle the "
            "imbalance.\n\n"
            "For the full training pipeline, model comparison (Isolation Forest, Random Forest, "
            "LSTM Autoencoder), SHAP analysis notebooks, and FastAPI inference endpoint, see the "
            "[GitHub repository](https://github.com/joshleh/secom-fault-detection)."
        )

    try:
        pipeline = load_pipeline()
    except Exception as e:
        st.error(
            f"**Failed to load pipeline artifacts.** Make sure you have run "
            f"`python src/train.py` and that `data/processed/` contains "
            f"`X_clean.csv` and `y.csv`.\n\nError: {e}"
        )
        return

    # ── Sidebar: page selector ────────────────────────────
    page = st.sidebar.radio(
        "View",
        [
            "Wafer Diagnostic",
            "Compare Wafers",
            "Aggregate Metrics",
            "Failure Clustering",
            "Drift Monitor",
        ],
        index=0,
        help=(
            "• Wafer Diagnostic — investigate one wafer in detail.\n"
            "• Compare Wafers — see what's different between two wafers.\n"
            "• Aggregate Metrics — how good is the model overall?\n"
            "• Failure Clustering — group failures into distinct failure modes.\n"
            "• Drift Monitor — has the production line changed since training?"
        ),
    )
    st.sidebar.markdown("---")

    if page == "Drift Monitor":
        render_drift_page(pipeline)
        return
    if page == "Compare Wafers":
        render_compare_page(pipeline)
        return
    if page == "Aggregate Metrics":
        render_metrics_page(pipeline)
        return
    if page == "Failure Clustering":
        render_clustering_page(pipeline)
        return

    # ── Sidebar: Sample selection ─────────────────────────
    st.sidebar.header("Select a Wafer")
    st.sidebar.caption(
        "Pick any wafer by number, or filter the list to show only passes / "
        "only failures. \"Manual sensor override\" lets you tweak a wafer's "
        "readings to see how the prediction would change — useful for "
        "what-if analysis."
    )

    mode = st.sidebar.radio(
        "Input mode",
        ["Pick a wafer", "Manual sensor override"],
        index=0,
    )

    if mode == "Pick a wafer":
        filter_type = st.sidebar.selectbox(
            "Show",
            ["All wafers", "Failed wafers only", "Passed wafers only"],
        )

        if filter_type == "Failed wafers only":
            valid_indices = pipeline.fail_indices
        elif filter_type == "Passed wafers only":
            valid_indices = pipeline.pass_indices
        else:
            valid_indices = list(range(pipeline.n_samples))

        sample_idx = st.sidebar.selectbox(
            f"Wafer # ({len(valid_indices)} available)",
            valid_indices,
            index=0,
            format_func=lambda x: x + 1,
            help="Each number corresponds to a different wafer in the dataset",
        )

        raw_features = pipeline.get_sample(sample_idx)
        actual_label = pipeline.get_label(sample_idx)
        actual_label_str = "FAIL" if actual_label == 1 else "PASS"

        st.sidebar.markdown(f"**Actual outcome:** {actual_label_str}")
    else:
        st.sidebar.markdown("Start from a base wafer, then tweak sensor values below to see how the prediction changes.")
        wafer_num = st.sidebar.number_input(
            "Base wafer #", min_value=1, max_value=pipeline.n_samples, value=1,
            help="Select a wafer to start from",
        )
        sample_idx = wafer_num - 1
        raw_features = pipeline.get_sample(sample_idx).copy()
        actual_label = pipeline.get_label(sample_idx)
        actual_label_str = "FAIL" if actual_label == 1 else "PASS"

    # ── Run diagnostics ──────────────────────────────────
    top_k = st.sidebar.slider("Top sensors to analyze", min_value=3, max_value=20, value=10)

    if mode == "Pick a wafer":
        # Use the cached helper for the common path; SHAP on the same wafer
        # only runs once per session.
        diag = _diagnose_cached(pipeline, int(sample_idx), top_k=top_k)
    else:
        diag = pipeline.diagnose_sample(raw_features, sample_index=sample_idx, top_k=top_k)

    # ── Manual override UI (after initial diagnosis to show feature names) ──
    if mode == "Manual sensor override":
        st.sidebar.markdown("---")
        st.sidebar.subheader("Override Sensor Values")
        overrides = {}
        for feat in diag.top_shap_features[:5]:
            current_val = float(raw_features.get(feat, 0.0))
            new_val = st.sidebar.number_input(
                f"{feat}", value=current_val, format="%.4f", key=f"override_{feat}"
            )
            if new_val != current_val:
                overrides[feat] = new_val

        if overrides:
            for feat_name in overrides:
                if feat_name in raw_features.index:
                    raw_features[feat_name] = overrides[feat_name]
            diag = pipeline.diagnose_sample(raw_features, sample_index=sample_idx, top_k=top_k)
            st.sidebar.success(f"Applied {len(overrides)} override(s). Results updated.")

    # ── Layout: Main panels ──────────────────────────────

    # ── Panel 1: Wafer Diagnostic Overview ──
    st.header("Wafer Diagnostic Overview")
    st.caption(
        "**When to use this view:** A specific wafer was flagged on the line, "
        "or you want to understand *why* the model predicts pass/fail for one "
        "wafer in particular. The four cards below summarize what the model "
        "says, what actually happened, and whether the two agree."
    )

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        pred_color = "🔴" if diag.prediction == "FAIL" else "🟢"
        st.metric("Prediction", f"{pred_color} {diag.prediction}")
    with col2:
        st.metric("Failure Probability", f"{diag.probability:.1%}",
                  help="Model's estimated chance this wafer fails quality inspection")
    with col3:
        st.metric("Actual Outcome", actual_label_str,
                  help="Ground truth: did this wafer actually pass or fail?")
    with col4:
        match = "✓ Correct" if (
            (diag.prediction == "FAIL" and actual_label == 1) or
            (diag.prediction == "PASS" and actual_label == 0)
        ) else "✗ Mismatch"
        st.metric("Model vs Actual", match,
                  help="Did the model's prediction agree with the real outcome?")

    # ── Panel 2: Top Sensor Drivers (SHAP) ──
    st.header("Top Sensor Drivers — *what made the model decide this?*")
    st.markdown(
        "Each bar is one sensor and shows how much that single sensor swung the "
        "prediction up or down. Think of it as *credit assignment*: the model "
        "starts from a neutral guess and each sensor reading pushes the verdict "
        "a little toward PASS or FAIL.\n\n"
        "- **Red bars** → this sensor's reading raised the failure probability.\n"
        "- **Blue bars** → this sensor's reading lowered it.\n"
        "- Longer bars = bigger influence.\n\n"
        "Under the hood this uses [SHAP](https://shap.readthedocs.io/) "
        "(SHapley Additive exPlanations), the standard method for breaking down "
        "an individual ML prediction into per-feature contributions."
    )

    top_features = diag.top_shap_features[:top_k]
    top_shap_vals = [float(diag.shap_values[f]) for f in top_features]

    colors = [COLORS["fail"] if v > 0 else COLORS["pass"] for v in top_shap_vals]

    fig_shap = go.Figure(go.Bar(
        x=top_shap_vals[::-1],
        y=top_features[::-1],
        orientation="h",
        marker_color=colors[::-1],
        text=[f"{v:+.4f}" for v in top_shap_vals[::-1]],
        textposition="auto",
        textfont=dict(color="#E0E0E0"),
    ))
    fig_shap.update_layout(
        xaxis_title="SHAP Value (contribution to failure prediction)",
        yaxis_title="Sensor (anonymized ID)",
        height=max(300, top_k * 35),
        margin=dict(l=20, r=20, t=10, b=40),
        **PLOTLY_LAYOUT,
    )
    st.plotly_chart(fig_shap, use_container_width=True)

    # ── Panel 3: Deviation from Healthy Baseline ──
    st.header("Deviation from Healthy Baseline — *how unusual are the readings?*")
    st.markdown(
        f"The model's verdict is more actionable when paired with the question: "
        f"*are these sensors actually behaving abnormally, or did the model just "
        f"latch onto noise?* This panel answers that.\n\n"
        f"The **baseline** is the average behavior of every sensor across "
        f"**{pipeline.baseline.n_samples} wafers that passed** quality inspection — "
        f"i.e., \"what normal production looks like.\" The **Z-score** below "
        f"says how many standard deviations this wafer's reading sits away from "
        f"that normal average:\n\n"
        f"- |Z| < 1 → essentially normal\n"
        f"- 1 ≤ |Z| < 2 → mild deviation\n"
        f"- |Z| ≥ 2 → unusually high or low (highlighted in the table)\n"
        f"- |Z| ≥ 3 → very rare under normal conditions — worth investigating first"
    )

    comparison_df = pipeline.get_baseline_comparison_df(diag, features=top_features)

    col_chart, col_table = st.columns([3, 2])

    with col_chart:
        z_vals = comparison_df["Z-Score"].values
        z_colors = [COLORS["fail"] if abs(z) > 2 else COLORS["warn"] if abs(z) > 1
                     else COLORS["ok"] for z in z_vals]

        fig_dev = go.Figure(go.Bar(
            x=z_vals,
            y=comparison_df["Sensor"].values,
            orientation="h",
            marker_color=z_colors,
            text=[f"{z:+.1f}σ" for z in z_vals],
            textposition="auto",
            textfont=dict(color="#E0E0E0"),
        ))
        fig_dev.add_vline(x=-2, line_dash="dash", line_color="#666", opacity=0.7)
        fig_dev.add_vline(x=2, line_dash="dash", line_color="#666", opacity=0.7)
        fig_dev.update_layout(
            xaxis_title="Z-Score (standard deviations from normal)",
            yaxis_title="Sensor (anonymized ID)",
            height=max(300, top_k * 35),
            margin=dict(l=20, r=20, t=10, b=40),
            **PLOTLY_LAYOUT,
        )
        st.plotly_chart(fig_dev, use_container_width=True)

    with col_table:
        def highlight_deviation(row):
            z = abs(row["Z-Score"])
            if z > 3:
                return ["background-color: #5c1a1a; color: #ff8a80"] * len(row)
            elif z > 2:
                return ["background-color: #4a3000; color: #ffcc80"] * len(row)
            return [""] * len(row)

        styled = comparison_df.style.apply(highlight_deviation, axis=1)
        st.dataframe(styled, use_container_width=True, hide_index=True)

    # ── Panel 4: Sample vs Baseline Overlay ──
    st.header("This Wafer vs Normal Range — *visual check*")
    st.markdown(
        "Same idea as the Z-score chart above, but plotted on the original sensor "
        "scale so the size of each deviation is easier to eyeball.\n\n"
        "- **Blue bars with whiskers** = the normal operating range for each "
        "sensor (mean ± 1 standard deviation, computed from passing wafers).\n"
        "- **Red diamonds** = this wafer's actual reading.\n\n"
        "Whenever a diamond sits far outside the blue bar, that sensor was running "
        "abnormally for this wafer."
    )

    overlay_features = top_features[:min(10, len(top_features))]
    sample_vals = [float(diag.feature_values[f]) for f in overlay_features]
    baseline_means = [float(pipeline.baseline.mean[f]) for f in overlay_features]
    baseline_stds = [float(pipeline.baseline.std[f]) for f in overlay_features]

    fig_overlay = go.Figure()
    fig_overlay.add_trace(go.Bar(
        name="Normal Range (passing wafers)",
        x=overlay_features,
        y=baseline_means,
        error_y=dict(type="data", array=baseline_stds, visible=True,
                     color="#78909C"),
        marker_color=COLORS["bar_baseline"],
        opacity=0.6,
    ))
    fig_overlay.add_trace(go.Scatter(
        name="This Wafer",
        x=overlay_features,
        y=sample_vals,
        mode="markers+lines",
        marker=dict(size=10, color=COLORS["sample_marker"], symbol="diamond"),
        line=dict(color=COLORS["sample_marker"], width=2),
    ))
    fig_overlay.update_layout(
        yaxis_title="Sensor Reading (scaled)",
        xaxis_title="Sensor (anonymized ID)",
        barmode="group",
        height=400,
        margin=dict(l=20, r=20, t=10, b=40),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        **PLOTLY_LAYOUT,
    )
    st.plotly_chart(fig_overlay, use_container_width=True)

    # ── Panel 5: Preliminary Failure Pattern Summary ──
    st.header("Plain-English Summary — *where would I start investigating?*")
    st.markdown(
        "*Auto-generated from the charts above (no LLM, no hallucination risk). "
        "It cross-references which sensors the model relied on most with which "
        "sensors deviate furthest from normal, so a process engineer has an "
        "immediate shortlist of suspects to check.*"
    )

    summary_text = generate_root_cause_summary(diag, pipeline.baseline, top_k=5)
    st.markdown(summary_text)

    # ── Panel 6: Raw Feature Inspector ──
    with st.expander("Full Feature Table (all 50 sensors used by the model)"):
        full_df = pd.DataFrame({
            "Sensor": diag.feature_values.index,
            "Value": diag.feature_values.values.round(4),
            "Baseline Mean": [round(float(pipeline.baseline.mean.get(f, 0)), 4)
                              for f in diag.feature_values.index],
            "Z-Score": diag.deviations_z.values.round(2),
            "SHAP": diag.shap_values.values.round(6),
        })
        full_df = full_df.sort_values("SHAP", key=lambda x: x.abs(), ascending=False)
        st.dataframe(full_df, use_container_width=True, hide_index=True, height=400)

    # ── Sidebar: Pipeline info ────────────────────────────
    st.sidebar.markdown("---")
    st.sidebar.subheader("Dataset & Model Info")
    fail_rate = len(pipeline.fail_indices) / pipeline.n_samples * 100
    n_estimators = getattr(pipeline.model, "n_estimators", "?")
    st.sidebar.markdown(f"""
    - **Total wafers:** {pipeline.n_samples}
    - **Passed:** {len(pipeline.pass_indices)} ({100 - fail_rate:.1f}%)
    - **Failed:** {len(pipeline.fail_indices)} ({fail_rate:.1f}%)
    - **Sensors used by model:** {len(pipeline.mi_selected_cols)} (selected from 590 original)
    - **Model:** Random Forest ({n_estimators} trees)
    - **Decision threshold:** {pipeline.threshold:.3f}
    """)


if __name__ == "__main__":
    main()
