"""
Semiconductor Yield Fault Detection

Interactive tool for inspecting individual wafers from a manufacturing
dataset. For each wafer, the dashboard shows:
  - pass/fail prediction from a trained Random Forest model
  - which sensors influenced the prediction most (SHAP)
  - how the wafer's readings compare to "normal" (passing) wafers
  - a plain-English diagnostic summary

Run:  streamlit run app/streamlit_app.py
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from src.diagnostics import DiagnosticsPipeline, generate_root_cause_summary

# ─── Page config ──────────────────────────────────────────

st.set_page_config(
    page_title="Yield Fault Detection",
    page_icon="🔬",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─── Dark-mode Plotly template ────────────────────────────

PLOTLY_LAYOUT = dict(
    template="plotly_dark",
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="rgba(0,0,0,0)",
    font=dict(family="sans-serif", color="#E0E0E0"),
)

COLORS = {
    "fail": "#EF5350",
    "pass": "#4FC3F7",
    "warn": "#FFA726",
    "ok": "#66BB6A",
    "bar_baseline": "#4FC3F7",
    "sample_marker": "#EF5350",
}

# ─── Pipeline loading (cached) ───────────────────────────

@st.cache_resource
def load_pipeline():
    """
    Load pipeline artifacts. Checks dashboard_assets/ first (committed to repo
    for zero-setup demos), then falls back to the standard data/ + models/ paths
    (generated by notebooks and train.py).
    """
    assets_dir = os.path.join(os.path.dirname(__file__), "..", "dashboard_assets")
    if os.path.isdir(os.path.join(assets_dir, "models")) and \
       os.path.isdir(os.path.join(assets_dir, "data")):
        model_dir = os.path.join(assets_dir, "models")
        data_dir = os.path.join(assets_dir, "data")
    else:
        model_dir = "models"
        data_dir = "data/processed"

    pipeline = DiagnosticsPipeline(model_dir=model_dir, data_dir=data_dir)
    pipeline.load()
    return pipeline


def main():
    # ── Header ────────────────────────────────────────────
    st.title("Semiconductor Yield Fault Detection")
    st.markdown(
        "Each row in this dataset represents one semiconductor wafer tested on a production line. "
        "Hundreds of sensors monitor the manufacturing process — this tool uses a trained ML model "
        "to predict whether a wafer will pass or fail quality inspection, and then explains "
        "**which sensors contributed most** to that prediction and **how far they deviate from normal**."
    )

    with st.expander("About this project & dataset"):
        st.markdown(
            "This dashboard is built on the [SECOM dataset](https://archive.ics.uci.edu/dataset/179/secom) "
            "from the UCI Machine Learning Repository. The data was collected from a real semiconductor "
            "manufacturing line — each of the 1,567 wafers has 590 sensor readings captured during "
            "production, along with a pass/fail quality label. The sensor names are anonymized to "
            "protect proprietary process details, so they appear as numeric IDs (e.g. Feature 1, "
            "Feature 155) rather than physical sensor names.\n\n"
            "Only ~6.6% of wafers in the dataset failed inspection, making this a heavily imbalanced "
            "classification problem. The ML pipeline behind this dashboard reduces the 590 raw sensors "
            "down to the 50 most informative features using variance filtering, correlation pruning, "
            "and mutual information ranking, then trains a class-weighted Random Forest to handle "
            "the imbalance.\n\n"
            "For the full training pipeline, model comparison (Isolation Forest, Random Forest, "
            "LSTM Autoencoder), SHAP analysis notebooks, and FastAPI inference endpoint, see the "
            "[GitHub repository](https://github.com/joshleh/secom-fault-detection)."
        )

    try:
        pipeline = load_pipeline()
    except Exception as e:
        st.error(
            f"**Failed to load pipeline artifacts.** Make sure you have run "
            f"`python src/train.py` and that `data/processed/` contains "
            f"`X_clean.csv` and `y.csv`.\n\nError: {e}"
        )
        return

    # ── Sidebar: Sample selection ─────────────────────────
    st.sidebar.header("Select a Wafer")
    st.sidebar.caption(
        "Each wafer in the dataset came from the production line. "
        "Pick a wafer by its number, or filter to only see wafers that passed or failed."
    )

    mode = st.sidebar.radio(
        "Input mode",
        ["Pick a wafer", "Manual sensor override"],
        index=0,
    )

    if mode == "Pick a wafer":
        filter_type = st.sidebar.selectbox(
            "Show",
            ["All wafers", "Failed wafers only", "Passed wafers only"],
        )

        if filter_type == "Failed wafers only":
            valid_indices = pipeline.fail_indices
        elif filter_type == "Passed wafers only":
            valid_indices = pipeline.pass_indices
        else:
            valid_indices = list(range(pipeline.n_samples))

        sample_idx = st.sidebar.selectbox(
            f"Wafer # ({len(valid_indices)} available)",
            valid_indices,
            index=0,
            format_func=lambda x: x + 1,
            help="Each number corresponds to a different wafer in the dataset",
        )

        raw_features = pipeline.get_sample(sample_idx)
        actual_label = pipeline.get_label(sample_idx)
        actual_label_str = "FAIL" if actual_label == 1 else "PASS"

        st.sidebar.markdown(f"**Actual outcome:** {actual_label_str}")
    else:
        st.sidebar.markdown("Start from a base wafer, then tweak sensor values below to see how the prediction changes.")
        wafer_num = st.sidebar.number_input(
            "Base wafer #", min_value=1, max_value=pipeline.n_samples, value=1,
            help="Select a wafer to start from",
        )
        sample_idx = wafer_num - 1
        raw_features = pipeline.get_sample(sample_idx).copy()
        actual_label = pipeline.get_label(sample_idx)
        actual_label_str = "FAIL" if actual_label == 1 else "PASS"

    # ── Run diagnostics ──────────────────────────────────
    top_k = st.sidebar.slider("Top sensors to analyze", min_value=3, max_value=20, value=10)

    diag = pipeline.diagnose_sample(raw_features, sample_index=sample_idx, top_k=top_k)

    # ── Manual override UI (after initial diagnosis to show feature names) ──
    if mode == "Manual sensor override":
        st.sidebar.markdown("---")
        st.sidebar.subheader("Override Sensor Values")
        overrides = {}
        for feat in diag.top_shap_features[:5]:
            current_val = float(raw_features.get(feat, 0.0))
            new_val = st.sidebar.number_input(
                f"{feat}", value=current_val, format="%.4f", key=f"override_{feat}"
            )
            if new_val != current_val:
                overrides[feat] = new_val

        if overrides:
            for feat_name in overrides:
                if feat_name in raw_features.index:
                    raw_features[feat_name] = overrides[feat_name]
            diag = pipeline.diagnose_sample(raw_features, sample_index=sample_idx, top_k=top_k)
            st.sidebar.success(f"Applied {len(overrides)} override(s). Results updated.")

    # ── Layout: Main panels ──────────────────────────────

    # ── Panel 1: Wafer Diagnostic Overview ──
    st.header("Wafer Diagnostic Overview")

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        pred_color = "🔴" if diag.prediction == "FAIL" else "🟢"
        st.metric("Prediction", f"{pred_color} {diag.prediction}")
    with col2:
        st.metric("Failure Probability", f"{diag.probability:.1%}",
                  help="Model's estimated chance this wafer fails quality inspection")
    with col3:
        st.metric("Actual Outcome", actual_label_str,
                  help="Ground truth: did this wafer actually pass or fail?")
    with col4:
        match = "✓ Correct" if (
            (diag.prediction == "FAIL" and actual_label == 1) or
            (diag.prediction == "PASS" and actual_label == 0)
        ) else "✗ Mismatch"
        st.metric("Model vs Actual", match,
                  help="Did the model's prediction agree with the real outcome?")

    # ── Panel 2: Top Sensor Drivers (SHAP) ──
    st.header("Top Sensor Drivers")
    st.markdown(
        "Each bar shows how much a single sensor influenced the model's prediction for this sample. "
        "This uses [SHAP](https://shap.readthedocs.io/) (SHapley Additive exPlanations), a method "
        "that breaks down a prediction into per-feature contributions. "
        "**Red bars** push toward FAIL; **blue bars** push toward PASS."
    )

    top_features = diag.top_shap_features[:top_k]
    top_shap_vals = [float(diag.shap_values[f]) for f in top_features]

    colors = [COLORS["fail"] if v > 0 else COLORS["pass"] for v in top_shap_vals]

    fig_shap = go.Figure(go.Bar(
        x=top_shap_vals[::-1],
        y=top_features[::-1],
        orientation="h",
        marker_color=colors[::-1],
        text=[f"{v:+.4f}" for v in top_shap_vals[::-1]],
        textposition="auto",
        textfont=dict(color="#E0E0E0"),
    ))
    fig_shap.update_layout(
        xaxis_title="SHAP Value (contribution to failure prediction)",
        yaxis_title="Sensor (anonymized ID)",
        height=max(300, top_k * 35),
        margin=dict(l=20, r=20, t=10, b=40),
        **PLOTLY_LAYOUT,
    )
    st.plotly_chart(fig_shap, use_container_width=True)

    # ── Panel 3: Deviation from Healthy Baseline ──
    st.header("Deviation from Healthy Baseline")
    st.markdown(
        f"The \"baseline\" is the average sensor behavior across **{pipeline.baseline.n_samples} wafers "
        f"that passed** quality inspection — this represents what normal production looks like. "
        f"The Z-score measures how many standard deviations this sample's reading is from that "
        f"normal average. A Z-score beyond **±2** means the sensor reading is unusually high or low "
        f"compared to healthy wafers (highlighted in the table)."
    )

    comparison_df = pipeline.get_baseline_comparison_df(diag, features=top_features)

    col_chart, col_table = st.columns([3, 2])

    with col_chart:
        z_vals = comparison_df["Z-Score"].values
        z_colors = [COLORS["fail"] if abs(z) > 2 else COLORS["warn"] if abs(z) > 1
                     else COLORS["ok"] for z in z_vals]

        fig_dev = go.Figure(go.Bar(
            x=z_vals,
            y=comparison_df["Sensor"].values,
            orientation="h",
            marker_color=z_colors,
            text=[f"{z:+.1f}σ" for z in z_vals],
            textposition="auto",
            textfont=dict(color="#E0E0E0"),
        ))
        fig_dev.add_vline(x=-2, line_dash="dash", line_color="#666", opacity=0.7)
        fig_dev.add_vline(x=2, line_dash="dash", line_color="#666", opacity=0.7)
        fig_dev.update_layout(
            xaxis_title="Z-Score (standard deviations from normal)",
            yaxis_title="Sensor (anonymized ID)",
            height=max(300, top_k * 35),
            margin=dict(l=20, r=20, t=10, b=40),
            **PLOTLY_LAYOUT,
        )
        st.plotly_chart(fig_dev, use_container_width=True)

    with col_table:
        def highlight_deviation(row):
            z = abs(row["Z-Score"])
            if z > 3:
                return ["background-color: #5c1a1a; color: #ff8a80"] * len(row)
            elif z > 2:
                return ["background-color: #4a3000; color: #ffcc80"] * len(row)
            return [""] * len(row)

        styled = comparison_df.style.apply(highlight_deviation, axis=1)
        st.dataframe(styled, use_container_width=True, hide_index=True)

    # ── Panel 4: Sample vs Baseline Overlay ──
    st.header("Sample vs Baseline Comparison")
    st.markdown(
        "Blue bars show the normal range (mean ± 1 standard deviation) for each sensor across "
        "passing wafers. Red diamonds show this sample's actual values. When a diamond falls "
        "far outside the blue bar, that sensor is behaving abnormally for this wafer."
    )

    overlay_features = top_features[:min(10, len(top_features))]
    sample_vals = [float(diag.feature_values[f]) for f in overlay_features]
    baseline_means = [float(pipeline.baseline.mean[f]) for f in overlay_features]
    baseline_stds = [float(pipeline.baseline.std[f]) for f in overlay_features]

    fig_overlay = go.Figure()
    fig_overlay.add_trace(go.Bar(
        name="Normal Range (passing wafers)",
        x=overlay_features,
        y=baseline_means,
        error_y=dict(type="data", array=baseline_stds, visible=True,
                     color="#78909C"),
        marker_color=COLORS["bar_baseline"],
        opacity=0.6,
    ))
    fig_overlay.add_trace(go.Scatter(
        name="This Wafer",
        x=overlay_features,
        y=sample_vals,
        mode="markers+lines",
        marker=dict(size=10, color=COLORS["sample_marker"], symbol="diamond"),
        line=dict(color=COLORS["sample_marker"], width=2),
    ))
    fig_overlay.update_layout(
        yaxis_title="Sensor Reading (scaled)",
        xaxis_title="Sensor (anonymized ID)",
        barmode="group",
        height=400,
        margin=dict(l=20, r=20, t=10, b=40),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        **PLOTLY_LAYOUT,
    )
    st.plotly_chart(fig_overlay, use_container_width=True)

    # ── Panel 5: Preliminary Failure Pattern Summary ──
    st.header("Preliminary Failure Pattern Summary")
    st.markdown(
        "*This summary is generated automatically from the model output and deviation data above — "
        "not by an LLM. It combines which sensors the model relied on most with which sensors "
        "deviate furthest from normal to suggest where to investigate.*"
    )

    summary_text = generate_root_cause_summary(diag, pipeline.baseline, top_k=5)
    st.markdown(summary_text)

    # ── Panel 6: Raw Feature Inspector ──
    with st.expander("Full Feature Table (all 50 sensors used by the model)"):
        full_df = pd.DataFrame({
            "Sensor": diag.feature_values.index,
            "Value": diag.feature_values.values.round(4),
            "Baseline Mean": [round(float(pipeline.baseline.mean.get(f, 0)), 4)
                              for f in diag.feature_values.index],
            "Z-Score": diag.deviations_z.values.round(2),
            "SHAP": diag.shap_values.values.round(6),
        })
        full_df = full_df.sort_values("SHAP", key=lambda x: x.abs(), ascending=False)
        st.dataframe(full_df, use_container_width=True, hide_index=True, height=400)

    # ── Sidebar: Pipeline info ────────────────────────────
    st.sidebar.markdown("---")
    st.sidebar.subheader("Dataset & Model Info")
    fail_rate = len(pipeline.fail_indices) / pipeline.n_samples * 100
    st.sidebar.markdown(f"""
    - **Total wafers:** {pipeline.n_samples}
    - **Passed:** {len(pipeline.pass_indices)} ({100 - fail_rate:.1f}%)
    - **Failed:** {len(pipeline.fail_indices)} ({fail_rate:.1f}%)
    - **Sensors used by model:** {len(pipeline.mi_selected_cols)} (selected from 590 original)
    - **Model:** Random Forest ({pipeline.model.n_estimators} trees)
    """)


if __name__ == "__main__":
    main()
